import {useMemo,useState} from 'react';
import {ArrowUpRight,ArrowRight,ArrowDown,TrendingUp,ShieldCheck,ChartNoAxesCombined,Info,RotateCcw,BriefcaseBusiness,UserRound,Check,ChevronDown,LockKeyhole,Leaf} from 'lucide-react';
import {calculate,type SimulationInput} from './tax/calculate';
import ComparisonChart,{compact} from './components/ComparisonChart';

const DEFAULT={income:'8000',investment:'3000',existing:'150',taxBase:'6000',comprehensive:'8000'};
const won=(v:number)=>`${new Intl.NumberFormat('ko-KR').format(v)}원`;
function MoneyField({label,value,onChange,hint}:{label:string;value:string;onChange:(v:string)=>void;hint?:string}){
 return <div className="field"><label>{label}<div className="money-input"><input type="number" min="0" max="100000000" step="1" value={value} onChange={e=>onChange(e.target.value)} aria-label={label}/><span>만원</span></div></label>{hint&&<p className="field-hint">{hint}</p>}</div>;
}
export default function App(){
 const [incomeType,setIncomeType]=useState<'salary'|'business'>('salary'); const [mode,setMode]=useState<'simple'|'detailed'>('simple');
 const [eligibilityConfirmed,setEligibilityConfirmed]=useState(false);
 const [comparisonAxis,setComparisonAxis]=useState<'investment'|'income'>('investment');
 const [scenario,setScenario]=useState<'example'|'actual'>('example'); const [values,setValues]=useState(DEFAULT); const [method,setMethod]=useState<'direct'|'fund'>('direct');
 const [investmentYear,setInvestmentYear]=useState(2026);const [claimOffset,setClaimOffset]=useState(0);
 const update=(key:keyof typeof DEFAULT)=>(value:string)=>setValues(v=>({...v,[key]:value}));
 const input:SimulationInput={incomeType,mode,scenario,income:Number(values.income)*10000,investment:Number(values.investment)*10000,existingDeductions:Number(values.existing)*10000,taxBase:Number(values.taxBase)*10000,comprehensiveIncome:Number(values.comprehensive)*10000,method,investmentYear,claimYear:investmentYear+claimOffset,eligibilityConfirmed};
 const calculation=useMemo(()=>{
 try{const required=mode==='simple'?['income','investment','existing'] as const:['taxBase','comprehensive','investment'] as const;
 if(required.some(k=>values[k].trim()==='')) throw new Error('금액을 모두 입력해 주세요. 0원도 입력할 수 있습니다.');
 return {result:calculate(input),error:''};}catch(e){return {result:null,error:(e as Error).message};}
 },[values,incomeType,mode,scenario,method,investmentYear,claimOffset,eligibilityConfirmed]);
 const r=calculation.result; const prefix=scenario==='example'?'예시':'예상';
 const incomeComparison=comparisonAxis==='income';
 const comparisonMax=Math.min(1e12,incomeComparison?Math.max(200000000,(mode==='simple'?input.income:input.taxBase)*1.3):Math.max(100000000,input.investment*1.3));
 const points=r?Array.from({length:41},(_,i)=>{const investment=Math.round(comparisonMax*i/40);const varied=incomeComparison?(mode==='simple'?{...input,income:investment}:{...input,taxBase:investment,comprehensiveIncome:Math.max(input.comprehensiveIncome,investment)}):{...input,investment};return {investment,saving:calculate(varied).saving};}):[];
 const ratio=r&&input.investment>0?r.saving/input.investment*100:0;
 const reset=()=>{setValues(DEFAULT);setIncomeType('salary');setMode('simple');setMethod('direct');setInvestmentYear(2026);setClaimOffset(0);setScenario('example');setEligibilityConfirmed(false);};
 return <><header className="header"><div className="nav"><a className="brand" href="#"><span className="brand-mark"><TrendingUp size={23}/></span>벤처핏<span className="brand-en">VENTUREFIT</span></a><nav aria-label="주 메뉴"><a className="nav-active" href="#simulator">절세 시뮬레이터</a><a href="#guide">계산 가이드</a></nav><span className="nav-note"><ShieldCheck size={15}/> 입력 정보 저장 없음</span></div></header>
 <main><section className="hero"><div><div className="eyebrow"><span/> SMART INVESTMENT, CLEAR NUMBERS</div><h1>투자의 가능성,<br/><span>절세까지 한눈에.</span></h1><p className="hero-copy">내 소득과 투자금으로 비교하는 벤처투자 소득공제.<br/>복잡한 숫자를, 이해하기 쉬운 그림으로 바꿔 드립니다.</p><div className="hero-tags"><span><Check size={14}/> 직장인·개인사업자</span><span><Check size={14}/> 소득별 비교</span><span><Check size={14}/> 가입 없이 바로</span></div></div><div className="hero-art" aria-hidden="true"><span className="orbit orbit-one"/><span className="orbit orbit-two"/><div className="art-chip"><ArrowUpRight size={17}/> 더 선명한 투자 계획</div><div className="art-bars"><span/><span/><span/><span/></div><div className="art-leaf"><Leaf size={35}/></div><div className="art-label">MAKE YOUR NEXT MOVE.</div></div></section>
 <div className="notice"><Info size={18}/><div><strong>{scenario==='example'?'예시 계산 · 실제 세금 산정용이 아닙니다':'세법 기준 · 실제 환급액과 다를 수 있습니다'}</strong><p>{scenario==='example'?'모든 연도에 동일한 예시 규칙을 적용합니다. 2026년 직접투자의 공제 요건을 확인했다면 세법 기준 모드를 선택하세요.':'2026년 공제 대상 직접투자·단일 소득을 기준으로 산출세액 차이를 추정합니다. 세액공제, 다른 감면과 기납부세액은 별도입니다.'}</p></div><span className="notice-pill">프로토타입</span></div>
 <section id="simulator" className="workspace"><aside className="panel input-panel"><div className="panel-heading"><div><span className="section-number">01</span><h2>나의 투자 조건</h2></div><button className="reset" onClick={reset} title="초기화" aria-label="입력 초기화"><RotateCcw size={16}/></button></div>
 <div className="input-body"><p className="label-text">소득 유형</p><div className="segment"><button className={incomeType==='salary'?'selected':''} aria-pressed={incomeType==='salary'} onClick={()=>setIncomeType('salary')}><UserRound size={16}/>직장인</button><button className={incomeType==='business'?'selected':''} aria-pressed={incomeType==='business'} onClick={()=>setIncomeType('business')}><BriefcaseBusiness size={16}/>개인사업자</button></div>
 <div className="mode-tabs"><button onClick={()=>setMode('simple')} className={mode==='simple'?'active':''}>간편 입력</button><button onClick={()=>setMode('detailed')} className={mode==='detailed'?'active':''}>상세 입력</button></div>
 {mode==='simple'?<><MoneyField label={incomeType==='salary'?'연간 총급여':'연간 사업소득'} value={values.income} onChange={update('income')} hint={incomeType==='salary'?'비과세 소득을 제외한 연간 총급여를 입력해 주세요.':'매출이 아닌, 필요경비를 뺀 사업소득을 입력해 주세요.'}/><MoneyField label="기존 소득공제 합계" value={values.existing} onChange={update('existing')} hint="인적공제·연금보험료 등. 근로소득공제와 투자 공제는 제외해 주세요."/></>:<><MoneyField label="투자 공제 전 과세표준" value={values.taxBase} onChange={update('taxBase')}/><MoneyField label="종합소득금액" value={values.comprehensive} onChange={update('comprehensive')} hint="공제 한도 계산에 사용합니다. 과세표준과 다른 금액입니다."/></>}
 <div className="input-divider"/><div className="field"><label>투자 방식<div className="select-wrap"><select value={method} onChange={e=>setMethod(e.target.value as 'direct'|'fund')}><option value="direct">벤처기업 직접투자 (제16조 제1항 제4호)</option><option value="fund">벤처투자조합 등 출자 · 예시</option></select><ChevronDown size={16}/></div></label><p className="field-hint">모든 상품이 공제 대상은 아닙니다. 실제 투자 경로별 요건 확인이 필요합니다.</p></div>
 {scenario==='actual'&&<label className="eligibility"><input type="checkbox" checked={eligibilityConfirmed} onChange={e=>setEligibilityConfirmed(e.target.checked)}/> <span>공제 요건 충족과 대상 투자금액을 확인했습니다.</span></label>}
 <MoneyField label="투자 금액" value={values.investment} onChange={update('investment')}/><div className="quick-values">{[1000,3000,5000,10000].map(v=><button key={v} className={Number(values.investment)===v?'chosen':''} onClick={()=>update('investment')(String(v))}>{v===10000?'1억원':`${v.toLocaleString()}만원`}</button>)}</div>
 <div className="year-inputs"><div className="field"><label>투자 연도<select aria-label="투자 연도" value={investmentYear} onChange={e=>setInvestmentYear(Number(e.target.value))}>{[2024,2025,2026,2027,2028].map(y=><option key={y}>{y}</option>)}</select></label></div><div className="field"><label>공제 적용 연도<select aria-label="공제 적용 연도" value={claimOffset} onChange={e=>setClaimOffset(Number(e.target.value))}>{[0,1,2].map(v=><option key={v} value={v}>{investmentYear+v}</option>)}</select></label></div></div>
 <div className="input-tip"><ShieldCheck size={16}/><p>입력값은 브라우저에서만 계산합니다.<br/>서버에 저장하거나 전송하지 않습니다.</p></div></div></aside>
 <div className="results"><div className="result-title"><div><span className="section-number">02</span><h2>숫자로 보는 투자 효과</h2></div><div className="scenario-switch"><button className={scenario==='example'?'active':''} onClick={()=>setScenario('example')}>예시 계산</button><button className={scenario==='actual'?'active':''} onClick={()=>setScenario('actual')}><ShieldCheck size={12}/> 실제 세법 적용</button></div></div>
 {!r?<div className="panel error-panel" role="alert"><Info size={28}/><h3>계산 조건을 확인해 주세요</h3><p>{calculation.error}</p>{scenario==='actual'&&<button className="primary-button" onClick={()=>setScenario('example')}>예시로 둘러보기 <ArrowRight size={16}/></button>}</div>:<>
 <div className="result-cards" aria-live="polite"><div className="saving-card"><div className="card-top"><span>{prefix} 절세액</span><ChartNoAxesCombined size={20}/></div><div className="big-value" data-testid="saving-value">{compact(r.saving)}<span>만원</span></div><div className="saving-footer"><span>투자금 대비 {ratio.toFixed(1)}%</span><span>지방소득세 포함</span></div></div><div className="metric-card"><span className="card-label">적용 소득공제액</span><div className="metric-value">{compact(r.appliedDeduction)}<span>만원</span></div><p>세금이 아닌, 과세 대상 소득의 감소</p></div><div className="metric-card"><span className="card-label">절세 반영 투자 부담액</span><div className="metric-value">{compact(r.burden)}<span>만원</span></div><p>투자금 − {prefix} 절세액</p></div></div>
 {mode==='simple'&&input.existingDeductions>r.comprehensiveIncome&&<div className="deduction-warning" role="status"><Info size={16}/><p>입력한 기존 공제액이 종합소득금액보다 큽니다. 과세표준은 0원으로 처리했습니다. 공제 내역을 확인해 주세요.</p></div>}
 <div className="panel tax-panel"><div className="subheading"><h3>공제 전후, 이렇게 달라져요</h3><span className="soft-pill">{prefix} · 산출세액 기준</span></div><div className="tax-comparison"><div><span className="muted-label">공제 전 소득세</span><strong>{won(r.beforeTax)}</strong><div className="tax-bar before"/></div><ArrowRight className="tax-arrow" size={22}/><div><span className="muted-label">공제 후 소득세</span><strong className="teal">{won(r.afterTax)}</strong><div className="tax-bar after" style={{width:`${r.beforeTax?Math.max(2,r.afterTax/r.beforeTax*100):0}%`}}/></div><div className="tax-difference"><ArrowDown size={16}/><strong>{compact(r.beforeTax-r.afterTax)}만원</strong><span>소득세 감소</span></div></div><div className="tax-note"><Info size={13}/> 실제 환급액은 세액공제·기납부세액 등에 따라 달라집니다.</div></div>
 <div className="panel chart-panel"><div className="chart-tabs"><button className={!incomeComparison?"active":""} onClick={()=>setComparisonAxis("investment")}>투자금별 비교</button><button className={incomeComparison?"active":""} onClick={()=>setComparisonAxis("income")}>소득별 비교</button></div><div className="subheading"><div><h3>{incomeComparison?"소득이 달라지면, 절세는 얼마나?":"투자금을 바꾸면, 절세는 얼마나?"}</h3><p>{incomeComparison?(mode==="simple"?"동일한 투자금·기존 공제액으로 소득만 바꿔 비교합니다.":"투자금은 고정하고 과세표준을 비교합니다. 소득금액은 기존 입력과 과세표준 중 큰 금액으로 가정합니다."):"현재 소득 조건을 유지한 비교입니다."}</p></div><span className="chart-legend"><span/> {prefix} 절세액</span></div><ComparisonChart points={points} isExample={scenario==='example'} current={incomeComparison?(mode==="simple"?input.income:input.taxBase):input.investment} axis={incomeComparison?"income":"investment"} xLabel={incomeComparison?(mode==="simple"?"소득":"과세표준"):"투자금"}/><div className="chart-insight"><TrendingUp size={18}/><p>투자금이 늘어도 공제 한도에 도달하면 절세 효과가 더 커지지 않을 수 있어요.</p></div></div>
 <div className="panel timeline-panel"><div className="subheading"><div><h3>언제 공제받을지 비교해 보세요</h3><p>같은 소득·세율 가정으로 비교합니다. 한 투자금은 한 번만 공제합니다.</p></div><span className="soft-pill">연도별 예시 비교</span></div><div className="timeline">{[0,1,2].map(v=><button key={v} className={`year-card ${claimOffset===v?'selected':''}`} onClick={()=>setClaimOffset(v)} aria-pressed={claimOffset===v}><div><span>{investmentYear+v}년</span>{claimOffset===v?<Check size={16}/>:<span className="year-dot"/>}</div><p>{v===0?'투자한 해':`투자 후 ${v}년`}</p><strong>{scenario==='actual'&&v!==0?'미확인':compact(r.saving)}<small>{scenario==='actual'&&v!==0?'':'만원'}</small></strong><span className="year-caption">{scenario==='actual'&&v!==0?'미래 세법 확인이 필요합니다':`이 연도 선택 시 ${prefix} 절세액`}</span></button>)}</div><p className="timeline-footnote">미래 소득과 세법이 달라지면 결과도 달라집니다. 연도별 금액을 합산하지 마세요.</p></div>
 <details className="panel breakdown"><summary>계산 과정 자세히 보기 <ChevronDown size={16}/></summary><dl><div><dt>종합소득금액</dt><dd>{won(r.comprehensiveIncome)}</dd></div><div><dt>투자 공제 전 과세표준</dt><dd>{won(r.taxBase)}</dd></div><div><dt>공제율로 산정한 공제액</dt><dd>{won(r.eligibleDeduction)}</dd></div><div><dt>소득 기준 한도 (50%)</dt><dd>{won(r.deductionLimit)}</dd></div><div><dt>적용한 공제액</dt><dd>{won(r.appliedDeduction)}</dd></div><div><dt>미적용 공제액 (이월 가정 없음)</dt><dd>{won(r.unusedDeduction)}</dd></div><div><dt>공제 후 과세표준</dt><dd>{won(r.afterTaxBase)}</dd></div><div><dt>사업소득 최저한세 (단일 소득 기준)</dt><dd>{won(r.minimumTax)}</dd></div><div><dt>지방소득세 감소분 가정</dt><dd>{won(r.localSaving)}</dd></div></dl></details>
 </>}</div></section>
 <section id="guide" className="guide"><div className="guide-heading"><span className="eyebrow">BEFORE YOU INVEST</span><h2>숫자 너머, 알아둘 것들</h2><p>더 나은 판단을 위한 세 가지 체크포인트.</p></div><div className="guide-grid"><article><span className="guide-icon"><ChartNoAxesCombined size={21}/></span><h3>소득공제 ≠ 세금 환급</h3><p>소득공제는 세금을 계산하는 소득을 줄입니다. 같은 공제액이라도 소득과 세율에 따라 줄어드는 세금이 달라집니다.</p></article><article><span className="guide-icon"><ShieldCheck size={21}/></span><h3>투자 대상과 요건을 확인하세요</h3><p>투자 방식, 기업의 자격, 증빙과 보유기간에 따라 공제 여부가 달라집니다. 중도 회수 시 추징 조건도 확인해야 합니다.</p></article><article><span className="guide-icon"><TrendingUp size={21}/></span><h3>절세가 수익을 보장하지 않아요</h3><p>투자 부담액은 원금 회수나 투자 수익을 뜻하지 않습니다. 벤처투자는 원금 손실과 유동성 위험이 있습니다.</p></article></div></section>
 <section className="methodology"><h3><Info size={17}/> 이 프로토타입의 계산 가정</h3><p>직접투자 예시는 투자금 3,000만원 이하 100%, 다음 2,000만원 70%, 초과분 30%를 가정합니다. 조합 출자 예시는 일괄 10%입니다. 종합소득금액의 50%와 남은 과세표준 중 작은 금액을 공제 한도로 가정하며, 지방소득세 감소분은 소득세 감소분의 10%로 계산합니다.</p><p>예시 모드는 모든 연도에 같은 가정으로 계산합니다. 세법 기준 모드는 2026년 직접투자와 2026년 공제만 지원합니다. 개인사업자는 사업소득만 있다고 가정하고 최저한세를 반영합니다. 지방소득세는 표준세율 기준 추정입니다. 세액공제, 다른 감면, 복합 소득, 다른 투자 공제와의 합산은 반영하지 않았습니다. 공제 요건과 증빙·보유기간을 별도로 확인하고 실제 신고에는 세무 검토가 필요합니다.</p><div className="source-links"><a href="https://www.law.go.kr/LSW/lsLinkProc.do?lsNm=조세특례제한법&joNo=001600000&mode=10" target="_blank" rel="noreferrer">조세특례제한법 제16조 <ArrowUpRight size={14}/></a><a href="https://www.nts.go.kr" target="_blank" rel="noreferrer">국세청 안내 확인 <ArrowUpRight size={14}/></a><span>2026년 공제율·한도·세율 공식 조문 확인</span></div></section>
 </main><footer><a className="brand" href="#"><span className="brand-mark small"><TrendingUp size={17}/></span>벤처핏</a><p>더 선명한 숫자, 더 신중한 투자.</p><span>벤처투자 시뮬레이터 · 개인정보 수집 없음</span></footer></>;
}
